### ISSUE TITLE
Some requests return error 500

### ISSUE THREAD

**Issue by pozemka** [chubin/cheat.sh#265] opened 2020-11-24 07:45 UTC
![изображение](https://user-images.githubusercontent.com/1259724/100063299-129e1000-2e42-11eb-8e57-114c233044ac.png)

however some are fine:
![изображение](https://user-images.githubusercontent.com/1259724/100063347-26e20d00-2e42-11eb-9a8a-12c61ac73c8d.png)

**Comment by vivienicepig** [comment] 2020-11-24 07:47
same problem here...
:(

**Comment by abitrolly** [comment] 2020-11-24 08:44
I see that my local server errors on both http://127.0.0.1:2999/cpp/measure and http://127.0.0.1:2999/cpp/ but not http://127.0.0.1:2999/cpp

The strange thing is that it still tries to connect to https://cheat.sh:443 and fails.
```
✗ runin-podman.sh -e CHEATSH_CACHE_TYPE=none -p 2999:8002 4cb
Starting gevent server on 0.0.0.0:8002
connectionpool.py:937: Starting new HTTPS connection (1): cheat.sh:443
connectionpool.py:433: https://cheat.sh:443 "GET /cpp/measure?add_comments=True&lang=en HTTP/1.1" 500 290
127.0.0.1 - - [2020-11-24 08:39:04] "GET /cpp/measure HTTP/1.1" 200 414394 0.720549
127.0.0.1 - - [2020-11-24 08:39:04] "GET /files/fonts/stylesheet.css HTTP/1.1" 404 356 0.001829
127.0.0.1 - - [2020-11-24 08:39:20] "GET /cpp HTTP/1.1" 200 415403 0.088433
127.0.0.1 - - [2020-11-24 08:39:20] "GET /files/fonts/stylesheet.css HTTP/1.1" 404 356 0.000843
connectionpool.py:937: Starting new HTTPS connection (1): cheat.sh:443
connectionpool.py:433: https://cheat.sh:443 "GET /cpp/measure?add_comments=True&lang=en HTTP/1.1" 500 290
127.0.0.1 - - [2020-11-24 08:39:26] "GET /cpp/measure HTTP/1.1" 200 414394 0.253823
127.0.0.1 - - [2020-11-24 08:39:26] "GET /files/fonts/stylesheet.css HTTP/1.1" 404 356 0.001229
...
```

**Comment by FraserYu** [comment] 2020-11-25 14:02
same problem here, 
![image](https://user-images.githubusercontent.com/10631001/100237366-d1088480-2f69-11eb-83bb-6b6e4acb635a.png)

host local server, seems no fonts files:
![image](https://user-images.githubusercontent.com/10631001/100237326-c4842c00-2f69-11eb-9fbd-3ea43a02bfdb.png)

**Comment by DrGonzoIII** [comment] 2020-11-25 17:21
I have the same problem.

**Comment by chubin** [comment] 2020-11-25 21:01
Please test now; there was a small bug

**Comment by vivienicepig** [comment] 2020-11-26 00:19
> Please test now; there was a small bug

it works !!

**Comment by abitrolly** [comment] 2020-11-26 04:41
I confirm there is 500 error right now. But https://cheat.sh/cpp and https://cheat.sh/cpp/ return different results for some reason.

Why does the local version need to connect to remote server?

**Comment by pozemka** [comment] 2020-11-26 16:50
Seems fixed for me.

**Comment by chubin** [comment] 2020-11-29 21:33
@abitrolly

`cpp` and `cpp/` differ because of the following reason (maybe we should automatically drop the slash, and convert `cpp/` into `cpp`; this would make sense):

* `cpp` is just a plain cheat sheet, nothing special;
* `cpp/` is an query about the C++ programming language, handnled by the `question` adapter (which is basically stackoverflow API wrapper + internal index + various optimizations).

Now about the question: 

> Why does the local version need to connect to remote server?

The problem is that the question adapter (mentioned above) is not yet fully integrated into the cheat.sh codebase, which I gradually do, but there are some blocks still that are not yet integrated. So this functionality is not available in the standalone deployments, and they use the main cheat.sh server as the upstream server. All other queries (except the queries processed by the `question` adapter) are processed fully locally without any connection to the upstream server.

**Comment by chubin** [comment] 2020-11-29 21:35
I close this issue, and let's continue our discussion about the architecture in more relevant issues, for example here: #231

**Closed** 2020-11-29 21:38 UTC
