### ISSUE TITLE
'e also' bug in `disown`

### ISSUE THREAD

**Issue by jcalbert** [chubin/cheat.sh#140] opened 2019-05-10 22:34 UTC
similar to #8 , cheat.sh/disown also contains

```
#
# e also: jobs
#
```

**Comment by chubin** [comment] 2019-05-11 16:51
@jcalbert Yes, it is known. The problem is already fixed in the new major update, which is about to be rolled out

**Comment by chubin** [comment] 2019-06-27 19:19
Fixed in the new cheat.sh version

**Closed by chubin** 2019-06-27 19:19 UTC
