### ISSUE TITLE
cht.sh shell script doesn't work after curl update

### ISSUE THREAD

**Issue by GokhanPolat** [chubin/cheat.sh#310] opened 2021-10-05 15:59 UTC
I have been facing this problem since I updated curl. After some analyze this issiue I ended up with ssl connection and certificate problem. I'm using cht.sh command from terminal. If you change the url in this shell script http://cht.sh (without ssl) instead of https, it's working as expected.
I think this issue comes from Let's Encrypt certs and curl fire up "SSL certificate problem". More info at https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021 and https://curl.haxx.se/docs/sslcerts.html

**Comment by 90th** [comment] 2021-12-14 04:45
Oh damn thanks for this!

**Comment by chubin** [comment] 2022-04-17 06:05
Do you still have this problem? Everything looks fine from my side:

```
$ curl --version
curl 7.82.0-DEV (x86_64-pc-linux-musl) libcurl/7.82.0-DEV OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 libssh2/1.10.0 nghttp2/1.46.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
```

**Comment by dotcs** [comment] 2022-05-03 16:32
I can confirm that the connection via https works without any issues from my side. `cht.sh python3 random list elements` returns a result and the `cht.sh` script is configured to use https.

```console
$ cat $(which cht.sh) | grep -i http
[ -z "$CHTSH_URL" ] && CHTSH_URL=https://cht.sh
See cheat.sh/:standalone or https://github.com/chubin/cheat.sh/README.md
    cht.sh --mode lite      # use https://cheat.sh/ only
  local url=https://github.com/chubin/cheat.sh
    cht.sh --mode lite      # use https://cheat.sh/ only
notified via a HTTP request about any cheat sheets changes. For that, please
with the ENTRY-POINT from the URL https://ENTRY-POINT/:actualize specified
```

and

```console
$ cat $(which cht.sh) | grep -i __CHTSH_VERSION | head -n 1
__CHTSH_VERSION=0.0.4
```

**Comment by abitrolly** [comment] 2022-05-05 11:56
https://cht.sh certificate expired on 18 Dec 2021 and has been fixed since then - https://github.com/chubin/cheat.sh/issues/321

If there is still problem with `curl`, please comment on this issue with `curl --version` details. Closing for now.

**Closed by abitrolly** 2022-05-05 11:56 UTC
Labels: waiting-for-feedback
