### ISSUE TITLE
head cheat sheet prevents update-all

### ISSUE THREAD

**Issue by mnott** [chubin/cheat.sh#303] opened 2021-09-04 05:41 UTC
When I've done update-all and try it again, it fails:

```bash
$ python3 lib/fetch.py update-all
/Users/mnott/.cheat.sh/upstream/late.nz
/Users/mnott/.cheat.sh/upstream/tldr
/Users/mnott/.cheat.sh/upstream/cheat.sheets
/Users/mnott/.cheat.sh/upstream/cheat.sheets
/Users/mnott/.cheat.sh/upstream/learnxinyminutes-docs
/Users/mnott/.cheat.sh/upstream/cheatsheets

ERROR:
---
fatal: ambiguous argument 'HEAD': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

---
Could not get list of pages to be updated: [Adapter: cheat (Cheat)]
/Users/mnott/.cheat.sh/upstream/RosettaCodeData
```

In order to get that printout, I've added

```python
    print(adptr.local_repository_location())
```

just at the top of 

```python
def _update_adapter(adptr):
```

into fetch.py. Now investigating further, I find that if I 

```bash
rm upstream/cheatsheets/head 
```

first, I can run the update.

Of course, I can rather

```bash
rm -rf upstream/cheatsheets && python3 lib/fetch.py fetch-all && python3 lib/fetch.py update-all
```

so that I keep the complete cheatsheet, but there should be a better way.

**Comment by abitrolly** [comment] 2021-09-04 09:15
I usually use https://github.com/ionelmc/python-hunter to build a big log and then take grep and a coffee to grep through it while troubleshooting such things.

**Comment by chubin** [comment] 2022-04-17 11:59
It is a useful tool (python-hunter). We should add a cheat sheet about it.

The problem is fixed now. Please test

**Closed** 2022-04-17 12:02 UTC
