### ISSUE TITLE
Access to RFCs via cheat.sh

### ISSUE THREAD

**Issue by ErezBinyamin** [chubin/cheat.sh#167] opened 2020-01-11 19:57 UTC
So I do a good deal of networking research and I love cheat.sh. I have a tool that I use that I think could be nicely integrated into cheat.sh

```
RFC_get () 
{ 
    [ $# -lt 1 ] && return 1
    isNum='^[0-9]+$'
    [[ ${1} =~ $isNum ]] || return 1
    curl "https://www.ietf.org/rfc/rfc${1}.txt"
}
```

Perhaps the usage syntax could be:
```
curl cheat.sh/RFC/${NUMBER}
```

And that URL could simply resolve to:
```
https://www.ietf.org/rfc/rfc${NUMBER}.txt
```

**Comment by chubin** [comment] 2020-01-11 21:56
@ErezBinyamin Thank you, Erez. It is a good idea. As the first step we should add RFCs to cheat.sh; even better would be to add some search feature, so that is would be possible to
get list of some RFCs by a keyword, or a list of related RFCs

**Comment by ErezBinyamin** [comment] 2020-01-12 20:50
I have never contributed to an open source project before, but I am a relativity experienced programmer. I would be happy to help adding this feature in whatever way makes the most sense. I'm not sure what the standard practice is (as this is my first time posting an "issue"), but I would like to contribute if possible :)

**Comment by chubin** [comment] 2020-03-22 14:03
@ErezBinyamin Erez hi!

Erez, sorry for the delay; I finally have some time for my opensource projects.

If you still have interest to the project, and you still want to contribute,
that is the next step that we should do:

* add some special mode to get the list of the available urls (`list`)

After that I could bind the function to cheat.sh.

Also, I am think about removing the pages header and footer
like this:

```
Arkko, et al.               Standards Track                     [Page 2]
^L
RFC 4567       Key Management Extensions for SDP and RTSP      July 2006
```

I understand that this is useful information (generally speaking),
but it is not very useful in the screen-oriented representation.

What do you think?

**Comment by ErezBinyamin** [comment] 2020-03-22 16:06
I totally agree. Less is more, no need for header and footer. I have beefed up my RFC_get function to be able to keyword search RFC's and output a list of related RFC's.

I'm sort of cheating by just using [this tool](https://www.rfc-editor.org/search/rfc_search.php) but hey it works :)

```bash
RFC_get ()
{
	[ $# -lt 1 ] && return 1
	RFC=/tmp/rfc.txt
	isNum='^[0-9]+$'

	if [[ ${1} =~ $isNum ]]
	then
		curl "https://www.ietf.org/rfc/rfc${1}.txt" 2>/dev/null > $RFC
	else
		curl "https://www.rfc-editor.org/search/rfc_search_detail.php?title=${1}&pubstatus%5B%5D=Any&pub_date_type=any" 2>/dev/null | sed 's/href="/\n/g; s/.html/.html\n/g' | grep 'http.*.html' | sed 's/.html*//g' | rev | sed 's/cfr.*//' | rev > $RFC
	fi
	cat $RFC | grep -q '<!DOCTYPE html>' && return 1 || cat $RFC
}
```

This bash function will either print the corresponding RFC by number, or output a list of RFC numbers related to a keyword. The top number is usually the RFC I'm looking for, and I could easily auto implement an "I'm feeling lucky" functionality, but I have found the list useful.

I think this could be a pretty cool addition. It would help me a lot if you could answer some questions:

1. What language would you like this function to be written in?
2. What arguments should it take?
3. What outputs should it produce?

Right now the answers are:
1. Bash
2. Any string
3. 
    - If the input argument is a number, print the corresponding RFC to the screen
    - If the number is invalid print nothing and return an error (1)
    - If the input is a string print a list of RFC numbers that may be relevant to that string

**Comment by ErezBinyamin** [comment] 2020-03-23 01:42
Removed Header and Footers too. As well as unnecessary blank space. I kept the top header, I kind of like a nice title header. The intermediary page breaks are gone now tho.
```bash
RFC_get()
{
	[ $# -lt 1 ] && return 1
	RFC=/tmp/rfc.txt
	isNum='^[0-9]+$'

	if [[ ${1} =~ $isNum ]]
	then
		curl "https://www.ietf.org/rfc/rfc${1}.txt" 2>/dev/null > $RFC
	else
		curl "https://www.rfc-editor.org/search/rfc_search_detail.php?title=${1}&pubstatus%5B%5D=Any&pub_date_type=any" 2>/dev/null | sed 's/href="/\n/g; s/.html/.html\n/g' | grep 'http.*.html' | sed 's/.html*//g' | rev | sed 's/cfr.*//' | rev > $RFC
	fi

	# Remove HEADER, and Footer sections
	sed -i '/RFC/d; /\[Page/d' $RFC

	cat $RFC | grep -q '<!DOCTYPE html>' && return 1 || cat -s $RFC
}
```

**Comment by chubin** [comment] 2020-03-23 12:03
It would be good to not depend on external services such as search, especially because we have our own search engine inside, but for the start we can use it too.

You have removed all headers and footers, and it looks much better now,
but there are still lines with `^L`:

```
[...]

   IPX encapsulation.

^L

   +---------------------+------------+-------------------------------+
   |                     |            |             |                 |
   |     IP Header       | UDP Header | IPX Header  | IPX packet data |
   | (20 or more octets) | (8 octets) | (30 octets) |                 |
   |                     |            |             |                 |
   +---------------------+------------+-------------------------------+

[...]
```

Probably, they should be cut out too?

Regarding the language, cheat.sh, is modular, and the adapters can be written
in any language, in shell too.
If it is a schell script, it must support several methods,
particularly `:list`, that lists all available topics.

For RFCs, it probably just should be something like `seq 1 MAX_RFC`?
Or do we have some holes in the sequence?

**Comment by ErezBinyamin** [comment] 2020-03-23 17:56
1. ^L now gone
2. `:list` argument supported pending completion of BAD_RFCS array

```bash
RFC_get()
{
	[ $# -lt 1 ] && return 1
	RFC=/tmp/rfc.txt
	BAD_RFCS=("8" "9" "14" "26" "51" "92")	# TODO find all "BAD RFCs"
	MAX_RFC=8650
	isNum='^[0-9]+$'

	# Get corresponding RFC by number
	if [[ ${1} =~ $isNum ]]
	then
		[ $1 -gt $MAX_RFC ] && return 1
		curl "https://www.ietf.org/rfc/rfc${1}.txt" 2>/dev/null > ${RFC}
	# Print list of available RFCs
	elif [[ "${1,,}" == ":list" ]]
	then
		for i in `seq 1 $MAX_RFC`
		do
			echo "${BAD_RFCS[@]}" | tr ' ' '\n' | grep -qFx $i || echo $i
		done
	else
	# Print list of RFCs related to keyword
		curl "https://www.rfc-editor.org/search/rfc_search_detail.php?title=${1}&pubstatus%5B%5D=Any&pub_date_type=any" 2>/dev/null | sed 's/href="/\n/g; s/.html/.html\n/g' | grep 'http.*.html' | sed 's/.html*//g' | rev | sed 's/cfr.*//' | rev > ${RFC}
	fi

	# Format nicely and print
	sed -i '/\[Page/,+2d; /\[page/,+2d;' ${RFC}
	cat ${RFC} | grep -q '<!DOCTYPE html>' && return 1 || cat -s ${RFC}
}

```

**Comment by chubin** [comment] 2020-03-29 18:33
Eric, I think that your script is slowly getting some real contour, and we can try to add to the repository and maybe install it on the live server.

What about the bad RFCs? Should we just make a look and go through all of them
and select the bad ones?

**Comment by ErezBinyamin** [comment] 2020-04-06 18:55
I just ran this guy:
```
for i in `seq 1 8650`; do curl --write-out %{http_code} --silent https://www.ietf.org/rfc/rfc${i}.txt 2>/dev/null | grep -q -e '404' -e 'was never issued' && echo $i; done
```
And updated the script accordingly.

**Comment by ErezBinyamin** [comment] 2020-04-06 21:21
There are two types of ""Bad RFC's":
1. Those that were never issued (ie: 3333, 6900).
2. Those that are not printable on the command line (PDF version only) (ie: 8, 51)

Here is an array of RFC's that were never issued
```
NEVER_ISSUED=( "3333" "3350" "3399" "3699" "3799" "3800" "3899" "3900" "3907" "3908" "3999" "4000" "4099" "4100" "4199" "4200" "4232" "4299" "4300" "4399" "4400" "4499" "4500" "4599" "4600" "4658" "4699" "4700" "4751" "4799" "4800" "4899" "4900" "4921" "4922" "4989" "4999" "5099" "5100" "5108" "5199" "5200" "5299" "5300" "5312" "5313" "5314" "5315" "5319" "5399" "5400" "5499" "5500" "5599" "5600" "5699" "5700" "5799" "5800" "5809" "5821" "5822" "5823" "5899" "5900" "5999" "6000" "6099" "6100" "6102" "6103" "6199" "6200" "6299" "6300" "6399" "6400" "6499" "6500" "6523" "6524" "6599" "6600" "6634" "6699" "6700" "6799" "6800" "6899" "6900" "6966" "6995" "6999" "7000" "7099" "7327" "7907" "8523" "8524" "8535" "8566" "8626" "8644" "8646" "8647" "8648" )
```

This newest script will print out a message like:  
> RFC \<N\> not issued.  

Some RFC's were issued but only exist in PDF form. For those it will print out a link to the PDF version of the RFC.

#Newest Script
```bash
RFC_get () 
{ 
    [ $# -lt 1 ] && return 1
    RFC=/tmp/rfc.txt
    MIN_RFC=1
    MAX_RFC=8650
    isNum='^[0-9]+$'
    if [[ ${1} =~ $isNum ]] then
        if [ $1 -gt $MAX_RFC ] || [ $1 -lt $MIN_RFC ] then
            echo "Valid RFC numbers: [ ${MIN_RFC} - ${MAX_RFC} ]"
            return 1
        fi
        curl "https://www.ietf.org/rfc/rfc${1}.txt" --write-out %{http_code} --silent --output ${RFC} 2> /dev/null | grep --color=auto -q '200'
        if [ $? -eq 0 ] then
            sed -i '/Page [0-9]/,+2d /page [0-9]/,+2d' ${RFC}
            cat ${RFC} | grep --color=auto -q '<!DOCTYPE html>' && return 1 || cat -s ${RFC}
            return 0
        fi
        curl "https://www.rfc-editor.org/info/rfc${1}" --write-out %{http_code} --silent --output ${RFC} 2> /dev/null | grep --color=auto -q '200'
        [ $? -eq 0 ] && grep --color=auto -o 'https.*\.pdf' ${RFC} || echo "RFC ${1} not issued"
    else
        if [[ "${1,,}" == ":list" ]] then
            for i in `seq 1 $MAX_RFC`
            do
                echo "${BAD_RFCS[@]}" | tr ' ' '\n' | grep --color=auto -qFx $i || echo $i
            done
        else
            ARG="${@}"
            curl "https://www.rfc-editor.org/search/rfc_search_detail.php?title=${ARG}" 2> /dev/null | sed 's/href="/\n/g s/.html/.html\n/g' | grep --color=auto -A 1 --color=auto 'http.*.html' | sed '/boldtext/d s/"target/<"target/g s/<[^>]*>//g /HTML,/d s/HTML// /--/d' | grep --color=auto -v -B 1 html | rev | sed 's/lmth\.// s/cfr.*// /--/d' | rev | sed 's/[A-Z]\..*// /mail-archive/,+1d s/^[ \t]*//' | sed 's/&nbsp.*//g s/<a//g N  s/\n/:\t/' > $RFC
        fi
    fi
}
```

**Comment by chubin** [comment] 2020-04-18 18:18
I've added your script + added a adapter for it, and deployed the changes.
Please test:

curl cht.sh/rfc/:list
curl cht.sh/rfc/1234

Also, if you use the command line client (cht.sh), tab completion should be supported too.
Please try:
```
cht.sh rfc/1<Tab>
```

I have two additional questions:
1. Why do you have range of the valid RFC numbers `Valid RFC numbers: [ 1 - 8650 ]` if the last one here is 8778? https://www.ietf.org/download/rfc-index.txt

2. Maybe we should download RFCs from IETF.org? Or not all RFCs are available there in plain text?

Anyway, please test

**Comment by ErezBinyamin** [comment] 2020-04-18 20:31
Through testing I have found that:  
 - ```curl cheat.sh/rfc/<NUMBER>``` works well.   
 - ```curl cheat.sh/rfc/:list``` works but the output is terrible and makes me sad (Update explained below).  
 - For some reason ```curl cheat.sh/rfc/<STRING>``` is not making it to my *related RFCs by keyword* function. I think something in ```cheat.sh``` is directing it away from the RFC_get function all together. 

I do not use the command line client ```cht.sh``` but I will set that up and give it a test run as well.  

1. I updated the [script](https://github.com/ErezBinyamin/Scripts/blob/master/tools/RFC_get.sh) to use the [rfc index](https://www.ietf.org/download/rfc-index.txt) to define MAX_RFC and to determine the output of ```:list``` (much better than a list of numbers).
 2. Not all RFC's are available in plain text, but we could download most of them. If we are missing one we could simply fall back on [IETF](https://www.ietf.org/rfc)

**Comment by chubin** [comment] 2020-04-19 14:05
>  Instead the program behaves as though the RFC adapter is not present. 

it was intended behavior of cheat.sh; I've changed it now in https://github.com/chubin/cheat.sh/commit/882438b1b765b79389bacbba4c28edc1360ee81e

```
$ curl cht.sh/rfc/ospf
1131:	OSPF specification 
1245:	OSPF Protocol Analysis  
1246:	Experience with the OSPF Protocol  
1247:	OSPF Version 2  
1248:	OSPF Version 2 Management Information Base  
1252:	OSPF Version 2 Management Information Base  
1253:	OSPF Version 2 Management Information Base  
1364:	BGP OSPF Interaction  
1370:	Applicability Statement for OSPF  Internet Architecture Board, 
1403:	BGP OSPF Interaction  
1583:	OSPF Version 2  
1584:	Multicast Extensions to OSPF 
1585:	MOSPF: Analysis and Experience  
1586:	Guidelines for Running OSPF Over Frame Relay Networks  
1587:	The OSPF NSSA Option  
1765:	OSPF Database Overflow  
1793:	Extending OSPF to Support Demand Circuits  
1850:	OSPF Version 2 Management Information Base  
2178:	OSPF Version 2 
2329:	OSPF Standardization Report  
2370:	The OSPF Opaque LSA Option 
```

Regading `:list`: list must have such format, otherwise tab completion would not work.
We can think about changing its format everywhere,
into something like:
```
topic1     short description of topic1
topic2     short description of topic2
...
```
But for the moment let us use some othe special query for that,
maybe `/:describe`?

```
curl cht.sh/rfc/:describe
```

If you would like to update the script, please make a PR, and I will merge it.

**Comment by ErezBinyamin** [comment] 2020-04-20 17:29
I have synced up [the script on my repo](https://github.com/ErezBinyamin/Scripts/blob/master/tools/RFC_get.sh) with [the script on your repo](https://github.com/chubin/cheat.sh/blob/master/share/adapters/rfc.sh).

I have implemented ```:list``` in the format you described and implemented a help message ```:usage```. I am about to make a PR so that you can merge the updates.

I am a bit confused about the proposed ```:describe``` feature. Do you mean a use case like:  

```curl cht.sh/rfc/:describe/3```

Where a short description of RFC 3 would be printed? Or am I misunderstanding?

**Comment by chubin** [comment] 2020-04-20 18:10
No, the idea was to keep `:list` in old format (just the list of topics aka RFC names)
and `:describe` for short descriptions, like this:
```
topic1     short description of topic1
topic2     short description of topic2
...
```

and *in future* (but we need to fix cht.sh for that) extend the existing `:list` format
so it will be the same as `:describe` now.

**Comment by ErezBinyamin** [comment] 2020-04-20 21:44
I made a Pull Request. It's the first PR I've ever made so my apologies if I did not make it properly. I think I implemented ```:list``` and ```:describe``` the way you specified. If I made an error please let me know.

**Comment by chubin** [comment] 2020-05-02 19:33
Erez hi! I've merged your pull-request, thank you for it. I commented out the two `printf`'s which print valid rfc ranges. It works like this:

```
curl cht.sh/rfc/:list                   # to list all available RFCs
curl cht.sh/rfc/:describe          # to list all available RFCs with short description
curl cht.sh/rfc/1234                 # to show RFC 1234
curl cht.sh/rfc/ospf                  # to list all RFCs with OSPF in the name
```

Also you can curl cht.sh/rfc to get this short description

**Comment by ErezBinyamin** [comment] 2020-05-03 14:20
This is amazing. It is better than what I imagined when I opened this issue! I've learned a lot from contributing here too, I hope users find the rfc adapter useful! I'd be happy to add any maintenance updates or additional functionality.

**Closed** 2020-05-03 14:23 UTC
