### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Flipun** [chubin/cheat.sh#113] opened 2018-10-17 07:12 UTC
https://github.com/chubin/cheat.sh/blob/master/README.md

<img width="835" alt="1" src="https://user-images.githubusercontent.com/32409266/47068398-c1f96900-d21e-11e8-9d0e-d0030bd12e5a.png">

In my Mac iTerm2, you must type 'curl cht.sh/lua/table+keys\?Q' or 'curl "cht.sh/lua/table+keys?Q"' because we need to escape characters.

**Comment by tsevans** [comment] 2019-10-30 16:46
Addressed this issue in #163, was a shell-specific issue but escaping the question mark is a universal solution.

**Comment by chubin** [comment] 2020-03-29 19:15
The problem was not because of iTerm2 itself, but because of tcsh/zsh.

I've merged the fix by Tom @tsevans 
and the problem is fixed now.

**Closed by chubin** 2020-03-29 19:15 UTC
