### ISSUE TITLE
 share/scripts/get-sheets.sh does not exist

### ISSUE THREAD

**Issue by Galphaa** [chubin/cheat.sh#192] opened 2020-05-09 09:37 UTC
Hello I am trying to build cheat.sh on local but I got error this error
sh: can't open 'share/scripts/get-sheets.sh': No such file or directory
in sourc files this file does not exist please provide

**Comment by chubin** [comment] 2020-05-21 17:49
@Galphaa Georgi, thank you for reporting it

It is a known issue; this script is not relevant anymore after the standalone mode was added. The Dockerfile must be fixed according to it. Feel free to help with it if you have time and inspiration. We would fix Dockerfile anyway, but with you help it would happen sooner :)

I will close this issue as a duplicate of #172

**Closed by chubin** 2020-05-21 17:49 UTC
